TABLE_STATES = {
    0: ['WorkingHour', 'Rainy', 'LowHungry', 'LowEnergy', 'LowMoney'],
    1: ['WorkingHour', 'Rainy', 'LowHungry', 'LowEnergy', 'MediumMoney'],
    2: ['WorkingHour', 'Rainy', 'LowHungry', 'LowEnergy', 'FullMoney'],
    3: ['WorkingHour', 'Rainy', 'LowHungry', 'MediumEnergy', 'LowMoney'],
    4: ['WorkingHour', 'Rainy', 'LowHungry', 'MediumEnergy', 'MediumMoney'],
    5: ['WorkingHour', 'Rainy', 'LowHungry', 'MediumEnergy', 'FullMoney'],
    6: ['WorkingHour', 'Rainy', 'LowHungry', 'FullEnergy', 'LowMoney'],
    7: ['WorkingHour', 'Rainy', 'LowHungry', 'FullEnergy', 'MediumMoney'],
    8: ['WorkingHour', 'Rainy', 'LowHungry', 'FullEnergy', 'FullMoney'],
    9: ['WorkingHour', 'Rainy', 'MediumHungry', 'LowEnergy', 'LowMoney'],
    10: ['WorkingHour', 'Rainy', 'MediumHungry', 'LowEnergy', 'MediumMoney'],
    11: ['WorkingHour', 'Rainy', 'MediumHungry', 'LowEnergy', 'FullMoney'],
    12: ['WorkingHour', 'Rainy', 'MediumHungry', 'MediumEnergy', 'LowMoney'],
    13: ['WorkingHour', 'Rainy', 'MediumHungry', 'MediumEnergy', 'MediumMoney'],
    14: ['WorkingHour', 'Rainy', 'MediumHungry', 'MediumEnergy', 'FullMoney'],
    15: ['WorkingHour', 'Rainy', 'MediumHungry', 'FullEnergy', 'LowMoney'],
    16: ['WorkingHour', 'Rainy', 'MediumHungry', 'FullEnergy', 'MediumMoney'],
    17: ['WorkingHour', 'Rainy', 'MediumHungry', 'FullEnergy', 'FullMoney'],
    18: ['WorkingHour', 'Rainy', 'FullHungry', 'LowEnergy', 'LowMoney'],
    19: ['WorkingHour', 'Rainy', 'FullHungry', 'LowEnergy', 'MediumMoney'],
    20: ['WorkingHour', 'Rainy', 'FullHungry', 'LowEnergy', 'FullMoney'],
    21: ['WorkingHour', 'Rainy', 'FullHungry', 'MediumEnergy', 'LowMoney'],
    22: ['WorkingHour', 'Rainy', 'FullHungry', 'MediumEnergy', 'MediumMoney'],
    23: ['WorkingHour', 'Rainy', 'FullHungry', 'MediumEnergy', 'FullMoney'],
    24: ['WorkingHour', 'Rainy', 'FullHungry', 'FullEnergy', 'LowMoney'],
    25: ['WorkingHour', 'Rainy', 'FullHungry', 'FullEnergy', 'MediumMoney'],
    26: ['WorkingHour', 'Rainy', 'FullHungry', 'FullEnergy', 'FullMoney'],
    27: ['WorkingHour', 'NotRainy', 'LowHungry', 'LowEnergy', 'LowMoney'],
    28: ['WorkingHour', 'NotRainy', 'LowHungry', 'LowEnergy', 'MediumMoney'],
    29: ['WorkingHour', 'NotRainy', 'LowHungry', 'LowEnergy', 'FullMoney'],
    30: ['WorkingHour', 'NotRainy', 'LowHungry', 'MediumEnergy', 'LowMoney'],
    31: ['WorkingHour', 'NotRainy', 'LowHungry', 'MediumEnergy', 'MediumMoney'],
    32: ['WorkingHour', 'NotRainy', 'LowHungry', 'MediumEnergy', 'FullMoney'],
    33: ['WorkingHour', 'NotRainy', 'LowHungry', 'FullEnergy', 'LowMoney'],
    34: ['WorkingHour', 'NotRainy', 'LowHungry', 'FullEnergy', 'MediumMoney'],
    35: ['WorkingHour', 'NotRainy', 'LowHungry', 'FullEnergy', 'FullMoney'],
    36: ['WorkingHour', 'NotRainy', 'MediumHungry', 'LowEnergy', 'LowMoney'],
    37: ['WorkingHour', 'NotRainy', 'MediumHungry', 'LowEnergy', 'MediumMoney'],
    38: ['WorkingHour', 'NotRainy', 'MediumHungry', 'LowEnergy', 'FullMoney'],
    39: ['WorkingHour', 'NotRainy', 'MediumHungry', 'MediumEnergy', 'LowMoney'],
    40: ['WorkingHour', 'NotRainy', 'MediumHungry', 'MediumEnergy', 'MediumMoney'],
    41: ['WorkingHour', 'NotRainy', 'MediumHungry', 'MediumEnergy', 'FullMoney'],
    42: ['WorkingHour', 'NotRainy', 'MediumHungry', 'FullEnergy', 'LowMoney'],
    43: ['WorkingHour', 'NotRainy', 'MediumHungry', 'FullEnergy', 'MediumMoney'],
    44: ['WorkingHour', 'NotRainy', 'MediumHungry', 'FullEnergy', 'FullMoney'],
    45: ['WorkingHour', 'NotRainy', 'FullHungry', 'LowEnergy', 'LowMoney'],
    46: ['WorkingHour', 'NotRainy', 'FullHungry', 'LowEnergy', 'MediumMoney'],
    47: ['WorkingHour', 'NotRainy', 'FullHungry', 'LowEnergy', 'FullMoney'],
    48: ['WorkingHour', 'NotRainy', 'FullHungry', 'MediumEnergy', 'LowMoney'],
    49: ['WorkingHour', 'NotRainy', 'FullHungry', 'MediumEnergy', 'MediumMoney'],
    50: ['WorkingHour', 'NotRainy', 'FullHungry', 'MediumEnergy', 'FullMoney'],
    51: ['WorkingHour', 'NotRainy', 'FullHungry', 'FullEnergy', 'LowMoney'],
    52: ['WorkingHour', 'NotRainy', 'FullHungry', 'FullEnergy', 'MediumMoney'],
    53: ['WorkingHour', 'NotRainy', 'FullHungry', 'FullEnergy', 'FullMoney'],
    54: ['FreeHour', 'Rainy', 'LowHungry', 'LowEnergy', 'LowMoney'],
    55: ['FreeHour', 'Rainy', 'LowHungry', 'LowEnergy', 'MediumMoney'],
    56: ['FreeHour', 'Rainy', 'LowHungry', 'LowEnergy', 'FullMoney'],
    57: ['FreeHour', 'Rainy', 'LowHungry', 'MediumEnergy', 'LowMoney'],
    58: ['FreeHour', 'Rainy', 'LowHungry', 'MediumEnergy', 'MediumMoney'],
    59: ['FreeHour', 'Rainy', 'LowHungry', 'MediumEnergy', 'FullMoney'],
    60: ['FreeHour', 'Rainy', 'LowHungry', 'FullEnergy', 'LowMoney'],
    61: ['FreeHour', 'Rainy', 'LowHungry', 'FullEnergy', 'MediumMoney'],
    62: ['FreeHour', 'Rainy', 'LowHungry', 'FullEnergy', 'FullMoney'],
    63: ['FreeHour', 'Rainy', 'MediumHungry', 'LowEnergy', 'LowMoney'],
    64: ['FreeHour', 'Rainy', 'MediumHungry', 'LowEnergy', 'MediumMoney'],
    65: ['FreeHour', 'Rainy', 'MediumHungry', 'LowEnergy', 'FullMoney'],
    66: ['FreeHour', 'Rainy', 'MediumHungry', 'MediumEnergy', 'LowMoney'],
    67: ['FreeHour', 'Rainy', 'MediumHungry', 'MediumEnergy', 'MediumMoney'],
    68: ['FreeHour', 'Rainy', 'MediumHungry', 'MediumEnergy', 'FullMoney'],
    69: ['FreeHour', 'Rainy', 'MediumHungry', 'FullEnergy', 'LowMoney'],
    70: ['FreeHour', 'Rainy', 'MediumHungry', 'FullEnergy', 'MediumMoney'],
    71: ['FreeHour', 'Rainy', 'MediumHungry', 'FullEnergy', 'FullMoney'],
    72: ['FreeHour', 'Rainy', 'FullHungry', 'LowEnergy', 'LowMoney'],
    73: ['FreeHour', 'Rainy', 'FullHungry', 'LowEnergy', 'MediumMoney'],
    74: ['FreeHour', 'Rainy', 'FullHungry', 'LowEnergy', 'FullMoney'],
    75: ['FreeHour', 'Rainy', 'FullHungry', 'MediumEnergy', 'LowMoney'],
    76: ['FreeHour', 'Rainy', 'FullHungry', 'MediumEnergy', 'MediumMoney'],
    77: ['FreeHour', 'Rainy', 'FullHungry', 'MediumEnergy', 'FullMoney'],
    78: ['FreeHour', 'Rainy', 'FullHungry', 'FullEnergy', 'LowMoney'],
    79: ['FreeHour', 'Rainy', 'FullHungry', 'FullEnergy', 'MediumMoney'],
    80: ['FreeHour', 'Rainy', 'FullHungry', 'FullEnergy', 'FullMoney'],
    81: ['FreeHour', 'NotRainy', 'LowHungry', 'LowEnergy', 'LowMoney'],
    82: ['FreeHour', 'NotRainy', 'LowHungry', 'LowEnergy', 'MediumMoney'],
    83: ['FreeHour', 'NotRainy', 'LowHungry', 'LowEnergy', 'FullMoney'],
    84: ['FreeHour', 'NotRainy', 'LowHungry', 'MediumEnergy', 'LowMoney'],
    85: ['FreeHour', 'NotRainy', 'LowHungry', 'MediumEnergy', 'MediumMoney'],
    86: ['FreeHour', 'NotRainy', 'LowHungry', 'MediumEnergy', 'FullMoney'],
    87: ['FreeHour', 'NotRainy', 'LowHungry', 'FullEnergy', 'LowMoney'],
    88: ['FreeHour', 'NotRainy', 'LowHungry', 'FullEnergy', 'MediumMoney'],
    89: ['FreeHour', 'NotRainy', 'LowHungry', 'FullEnergy', 'FullMoney'],
    90: ['FreeHour', 'NotRainy', 'MediumHungry', 'LowEnergy', 'LowMoney'],
    91: ['FreeHour', 'NotRainy', 'MediumHungry', 'LowEnergy', 'MediumMoney'],
    92: ['FreeHour', 'NotRainy', 'MediumHungry', 'LowEnergy', 'FullMoney'],
    93: ['FreeHour', 'NotRainy', 'MediumHungry', 'MediumEnergy', 'LowMoney'],
    94: ['FreeHour', 'NotRainy', 'MediumHungry', 'MediumEnergy', 'MediumMoney'],
    95: ['FreeHour', 'NotRainy', 'MediumHungry', 'MediumEnergy', 'FullMoney'],
    96: ['FreeHour', 'NotRainy', 'MediumHungry', 'FullEnergy', 'LowMoney'],
    97: ['FreeHour', 'NotRainy', 'MediumHungry', 'FullEnergy', 'MediumMoney'],
    98: ['FreeHour', 'NotRainy', 'MediumHungry', 'FullEnergy', 'FullMoney'],
    99: ['FreeHour', 'NotRainy', 'FullHungry', 'LowEnergy', 'LowMoney'],
    100: ['FreeHour', 'NotRainy', 'FullHungry', 'LowEnergy', 'MediumMoney'],
    101: ['FreeHour', 'NotRainy', 'FullHungry', 'LowEnergy', 'FullMoney'],
    102: ['FreeHour', 'NotRainy', 'FullHungry', 'MediumEnergy', 'LowMoney'],
    103: ['FreeHour', 'NotRainy', 'FullHungry', 'MediumEnergy', 'MediumMoney'],
    104: ['FreeHour', 'NotRainy', 'FullHungry', 'MediumEnergy', 'FullMoney'],
    105: ['FreeHour', 'NotRainy', 'FullHungry', 'FullEnergy', 'LowMoney'],
    106: ['FreeHour', 'NotRainy', 'FullHungry', 'FullEnergy', 'MediumMoney'],
    107: ['FreeHour', 'NotRainy', 'FullHungry', 'FullEnergy', 'FullMoney']
}

TABLE_ACTIONS = {
    0: 'Home',
    1: 'Work',
    2: 'Resto'
}

DISCOUNT_FACTOR = 0.9
FINAL_EXPLORATION_RATE = 0.1
START_EXPLORATION_RATE = 0.9
EPLORATION_RATE_DECAY_STEPS = 100
MAX_TIME_STEP = 24
NUM_STATE_DISCRETE = 108
NUM_STATE = 5
NUM_ACTION = 3